Repository GDSC-SKHU/Bakku-General-Server, pull requests merged in 2023-03, with the labels that each got.

#30 개발한 API들 문서화
  .docs/openapi.yaml
  .github/workflows/ci-cd.yml
  build.gradle
  src/main/java/com/gdsc/bakku/auth/controller/AuthController.java
  src/main/java/com/gdsc/bakku/bakku/controller/BakkuController.java
  src/main/java/com/gdsc/bakku/bakku/dto/request/BakkuFieldRequest.java
  src/main/java/com/gdsc/bakku/bakku/dto/request/BakkuImageRequest.java
  src/main/java/com/gdsc/bakku/bakku/dto/request/BakkuRequest.java
  src/main/java/com/gdsc/bakku/bakku/dto/response/BakkuResponse.java
  src/main/java/com/gdsc/bakku/common/annotation/CustomPageableAsQueryParam.java
  src/main/java/com/gdsc/bakku/common/response/FailureResponseBody.java
  src/main/java/com/gdsc/bakku/config/OpenApiConfig.java
  src/main/java/com/gdsc/bakku/config/SecurityConfig.java
  src/main/java/com/gdsc/bakku/event/controller/EventController.java
  src/main/java/com/gdsc/bakku/event/dto/EventDTO.java
  src/main/java/com/gdsc/bakku/ocean/controller/OceanController.java
  src/main/java/com/gdsc/bakku/ocean/dto/OceanDTO.java
  src/main/resources/application.yml
Labels: documentation

#29 랭킹 API
  build.gradle
  src/main/java/com/gdsc/bakku/bakku/controller/BakkuController.java
  src/main/java/com/gdsc/bakku/bakku/dto/response/GroupResponse.java
  src/main/java/com/gdsc/bakku/bakku/service/BakkuService.java
  src/main/java/com/gdsc/bakku/config/GroupRedisConfig.java
  src/main/java/com/gdsc/bakku/config/RedisConfig.java
  src/main/java/com/gdsc/bakku/group/domain/entity/Group.java
  src/main/java/com/gdsc/bakku/group/service/GroupService.java
  src/main/java/com/gdsc/bakku/rank/controller/RankingController.java
  src/main/java/com/gdsc/bakku/rank/service/RankingService.java
  src/main/java/com/gdsc/bakku/redis/service/RedisService.java
  src/main/resources/application.yml
Labels: feature

#36 Bakku Repsonse Sorting Issue
  src/main/java/com/gdsc/bakku/bakku/controller/BakkuController.java
  src/main/java/com/gdsc/bakku/bakku/domain/entity/Bakku.java
  src/main/java/com/gdsc/bakku/bakku/domain/repo/BakkuRepositorySupport.java
  src/main/java/com/gdsc/bakku/bakku/dto/response/BakkuResponse.java
Labels: bug

#32 신고 api
  src/main/java/com/gdsc/bakku/bakku/controller/BakkuController.java
  src/main/java/com/gdsc/bakku/bakku/domain/repo/BakkuRepositorySupport.java
  src/main/java/com/gdsc/bakku/bakku/service/BakkuService.java
  src/main/java/com/gdsc/bakku/common/error/StatusEnum.java
  src/main/java/com/gdsc/bakku/common/exception/AlreadyReportException.java
  src/main/java/com/gdsc/bakku/report/controller/ReportController.java
  src/main/java/com/gdsc/bakku/report/domain/entitiy/Report.java
  src/main/java/com/gdsc/bakku/report/domain/repo/ReportRepository.java
  src/main/java/com/gdsc/bakku/report/service/ReportService.java
Labels: feature

#41 204 처리하기
  src/main/java/com/gdsc/bakku/bakku/controller/BakkuController.java
Labels: feature
