Repository GDSC-SKHU/Bakku-General-Server, pull requests merged in 2023-02, with the labels that each got.

#6 Initialize Project
  build.gradle
  src/main/java/com/gdsc/bakku/common/entity/BaseTimeEntity.java
  src/main/java/com/gdsc/bakku/config/JpaAuditingConfig.java
  src/main/java/com/gdsc/bakku/config/SecurityConfig.java
  src/main/java/com/gdsc/bakku/event/domain/entity/Event.java
  src/main/java/com/gdsc/bakku/event/domain/repo/EventRepository.java
  src/main/java/com/gdsc/bakku/storage/domain/entity/Image.java
  src/main/java/com/gdsc/bakku/storage/domain/repo/ImageRepository.java
  src/main/resources/application.yml
Labels: feature

#9 이미지 관리 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/gdsc/bakku/storage/service/GCSService.java
  src/main/java/com/gdsc/bakku/storage/service/ImageService.java
  src/main/resources/application.yml
Labels: feature

#10 CI/CD 기능 추가
  .github/.workflows/ci-cd.yml
  build.gradle
  src/main/resources/application.yml
Labels: feature

#11 행사 API 추가
  src/main/java/com/gdsc/bakku/event/controller/EventController.java
  src/main/java/com/gdsc/bakku/event/domain/repo/EventRepository.java
  src/main/java/com/gdsc/bakku/event/service/EventService.java
Labels: feature

#19 에러 핸들링 커스텀
  src/main/java/com/gdsc/bakku/common/error/StatusEnum.java
  src/main/java/com/gdsc/bakku/common/exception/CouldNotGenerateInputStreamException.java
  src/main/java/com/gdsc/bakku/common/exception/CustomAbstractException.java
  src/main/java/com/gdsc/bakku/common/exception/EventNotFoundException.java
  src/main/java/com/gdsc/bakku/common/exception/GCSFIleNotFoundException.java
  src/main/java/com/gdsc/bakku/common/exception/NotSupportFileFormatException.java
  src/main/java/com/gdsc/bakku/common/exception/OceanNotFoundException.java
  src/main/java/com/gdsc/bakku/common/response/FailureResponseBody.java
  src/main/java/com/gdsc/bakku/config/GlobalExceptionHandler.java
  src/main/java/com/gdsc/bakku/event/service/EventService.java
  src/main/java/com/gdsc/bakku/ocean/service/OceanService.java
  src/main/java/com/gdsc/bakku/storage/service/GCSService.java
  src/main/java/com/gdsc/bakku/storage/service/ImageService.java
Labels: feature

#23 Fix User Update
  src/main/java/com/gdsc/bakku/auth/domain/entity/User.java
  src/main/java/com/gdsc/bakku/auth/filter/FirebaseTokenFilter.java
  src/main/java/com/gdsc/bakku/auth/service/UserService.java
Labels: bug

#25 문서화
  .docs/openapi.yaml
  .github/workflows/ci-cd.yml
  src/main/java/com/gdsc/bakku/common/entity/Location.java
  src/main/java/com/gdsc/bakku/common/entity/Position.java
  src/main/java/com/gdsc/bakku/common/error/StatusEnum.java
  src/main/java/com/gdsc/bakku/common/exception/InvalidPositionException.java
  src/main/java/com/gdsc/bakku/event/controller/EventController.java
  src/main/java/com/gdsc/bakku/event/domain/entity/Event.java
  src/main/java/com/gdsc/bakku/event/dto/EventDTO.java
  src/main/java/com/gdsc/bakku/event/service/EventService.java
  src/main/java/com/gdsc/bakku/ocean/controller/OceanController.java
  src/main/java/com/gdsc/bakku/ocean/domain/entity/Ocean.java
  src/main/java/com/gdsc/bakku/ocean/domain/repo/OceanRepositorySupport.java
  src/main/java/com/gdsc/bakku/ocean/dto/OceanDTO.java
  src/main/java/com/gdsc/bakku/ocean/service/OceanService.java
Labels: documentation
